### ISSUE TITLE
Accessing a server defined by django-ldapdb?

### ISSUE THREAD

**Issue by lofidevops** [asyd/pyldap_orm#1]
I'm using [django-ldapdb](https://github.com/django-ldapdb/django-ldapdb) to define a connection and Django-compatible ORM for LDAP. In some cases, though, I don't need the ORM to be a Django model. Is it possible for `pyldap_orm` to talk to an LDAP server connection defined by `django-ldapdb`?

(I'm on Python 3, so they're both wrapping `pyldap`)

**Comment by asyd** [comment]
Well, at least you should be able to initialise `pyldap_orm` using `django-ldapdb` configuration. 

But I'm not sure to understand your use cases, using both libs will require you having two kind of LDAP models.

**Comment by lofidevops** [comment]
I imagined that for some models Django integration was unnecessary (amongst other things they trigger the creation of Django migration scripts), and that I might like to share models between a Django and non-Django app. But on reflection my use cases are less likely (for me) than I first imagined, so I'm happy to leave the query there. Thanks for your time and a brilliant library.
